apiVersion: v1
kind: ConfigMap
metadata:
  name: m3db-datasource
  labels:
    grafana_datasource: "1"
data:
  m3db-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: M3DB
      type: prometheus
      access: proxy
      url: http://m3coordinator-m3db-cluster:7201
      version: 1
