apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: metakube-all
  namespace: default
spec:
  commonName: '*.k8s-monitoring.plgrnd.be'
  dnsNames:
    - '*.k8s-monitoring.plgrnd.be'
  secretName: metakube-tls-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
