apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
spec:
  endpoints:
    - interval: 30s
      params:
        module:
          - http_2xx
        target:
          - https://www.syseleven.de/
      path: "/probe"
      targetPort: exporter
      relabelings:
        - sourceLabels:
            - __param_target
          targetLabel: target
        - sourceLabels:
            - __param_module
          targetLabel: module
  namespaceSelector:
    matchNames:
      - <YOURNAME>
  selector:
    app: blackbox-exporter
