kind: Secret
apiVersion: v1
metadata:
  name: {{ include "web-application.fullname" . }}
  labels:
{{ include "web-application.labels" . | indent 4 }}
data:
  passcode.txt: {{ .Values.passcode | b64enc }}
