apiVersion: v1
kind: Service
metadata:
  name: web-application
  labels:
{{ include "web-application.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "web-application.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
